
CREATE TYPE order_status AS ENUM (
    'pending',
    'completed',
    'cancelled'
);

CREATE TABLE orders(
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id      INT NOT NULL,

    total_item   INT NOT NULL CHECK (total_item > 0),
    total_price  NUMERIC(10, 2) NOT NULL CHECK (total_price >= 0),
    
    order_status order_status DEFAULT 'pending',

    created_at   TIMESTAMP DEFAULT now(),

    updated_at   TIMESTAMP DEFAULT now(),

    CONSTRAINT fk_orders_user
        FOREIGN KEY(user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);


CREATE INDEX idx_orders_user_id ON orders(user_id);
CREATE INDEX idx_orders_created_at ON orders(created_at);
