CREATE TYPE product_category AS ENUM (
    'electronics',
    'clothing',
    'home_kitchen',
    'books',
    'beauty_personal_care',
    'sports_outdoors',
    'other'
);


CREATE TABLE products (
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name         VARCHAR(100) NOT NULL,
    description  TEXT NOT NULL,

    stock_qty    INT NOT NULL CHECK (stock_qty >= 0),
    category     product_category NOT NULL DEFAULT 'other',

    price        NUMERIC(10, 2) NOT NULL CHECK (price >= 0),
    rating       INT NOT NULL CHECK (rating BETWEEN 1 AND 5),

    created_at   TIMESTAMP DEFAULT now()
);

CREATE INDEX idx_products_name ON products(name);
CREATE INDEX idx_products_category ON products(category);
