CREATE TABLE user_addresses(
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id     INT NOT NULL,

    country     VARCHAR(100) NOT NULL,
    city        VARCHAR(100) NOT NULL,
    street      VARCHAR(500) NOT NULL,
    pincode     VARCHAR(20) NOT NULL,

    created_at   TIMESTAMP DEFAULT now(),

    CONSTRAINT fk_user_addresses 
        FOREIGN KEY (user_id) 
        REFERENCES users(id) 
        ON DELETE CASCADE
);

CREATE INDEX idx_user_country ON user_addresses(country);
CREATE INDEX idx_user_city ON user_addresses(city);