CREATE TABLE users(
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,    
    email       VARCHAR(100) UNIQUE NOT NULL,
    name        VARCHAR(100) NOT NULL,
    created_at  TIMESTAMP DEFAULT now()
);